# Netlify Configuration
# 
# This configuration file sets up:
# - Build settings for the React application
# - Redirects to map /api/* to serverless functions
# - Headers for security and CORS

[build]
  # Directory to publish (Vite output)
  publish = "dist"
  
  # Build command
  command = "npm run build"

# Redirect /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
