name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    name: Deploy Edge Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install supabase CLI
        run: npm install -g supabase

      - name: Deploy Edge Functions to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -euo pipefail
          echo "Authenticating supabase CLI"
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          echo "Linking project (safe if already linked)"
          supabase link --project-ref "$SUPABASE_PROJECT_REF" || true

          if [ -d "./functions" ]; then
            echo "Found ./functions directory. Deploying each function subdirectory..."
            for d in ./functions/*; do
              if [ -d "$d" ]; then
                name=$(basename "$d")
                echo "Deploying function: $name"
                # Deploy function by name; supabase CLI expects functions/<name>/...
                supabase functions deploy "$name" --project-ref "$SUPABASE_PROJECT_REF" || {
                  echo "Deployment failed for function $name"
                  exit 1
                }
              fi
            done
          else
            echo "No ./functions directory found — skipping function deploy"
          fi
